; Arquivo de Configuração do Projeto PlatformIO
;
;   Opções de build: flags de compilação, filtro de fontes
;   Opções de upload: porta de upload customizada, velocidade e flags extras
;   Opções de bibliotecas: dependências, storages extras de bibliotecas
;   Opções avançadas: scripts extras
;
; Consulte a documentação para outras opções e exemplos
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.13.0
framework = espidf
board = esp32dev
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
    -D BAUD_RATE=${env:esp32dev.monitor_speed}
check_tool = clangtidy, cppcheck
check_flags =
    clangtidy: --config-file=.clang-tidy
    cppcheck: --enable=warning,style --suppressions-list=.cppcheck-suppressions
check_skip_packages = yes
check_src_filters =
    +<src/>
    +<lib/>
    -<.pio/>
